---
- name: Create a Unique S3 Bucket
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws

  vars:
    aws_region: ap-south-1
    bucket_name: "ansible-bucket-{{ 99999999 | random }}"

  tasks:
    - name: Create S3 bucket with random name (no ACL)
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        region: "{{ aws_region }}"
        state: present
      register: s3_result

    - name: Show bucket name
      debug:
        msg: "S3 bucket '{{ bucket_name }}' created successfully."
