---
- name: Launch EC2 instance
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws

  vars:
    aws_region: ap-south-1
    instance_type: t2.micro
    ami_id: ami-02d26659fd82cf299  # Example: Ubuntu 20.04 LTS in us-east-1 (update for your region)
    key_name: GitLab             # Your existing EC2 key pair name
    security_group: sg-0a3096031971b0b2c      # Your security group ID
    subnet_id: subnet-0f6e986329dd3251c       # Your subnet ID (optional)

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "MyTestInstance"
        key_name: "{{ key_name }}"
        region: "{{ aws_region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_groups:
          - "{{ security_group }}"  # Correct parameter
        subnet_id: "{{ subnet_id }}"
        wait: yes
        count: 1
        state: present
      register: ec2

    - name: Show instance info
      debug:
        var: ec2.instances
