---
- name: Create users and groups, and add users to groups
  hosts: all
  become: yes

  vars:
    custom_groups:
      - devs
      - admins

    users:
      - name: alice
        groups: 
          - devs
      - name: bob
        groups:
          - admins
          - devs
      - name: charlie
        groups: []

  tasks:
    - name: Create groups
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ custom_groups }}"

    - name: Create users and add to groups
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups | join(',') }}"
        append: yes
        state: present
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"
